services:
  postgres-database:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: weatherForecast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02_data.sql:ro

volumes:
  postgres_data: