services:
  postgres-database:
    image: 'postgres:latest'
    container_name: postgres-database
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: weatherForecast
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/01_schema.sql