spring.application.name=weather

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/weatherForecast}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=${SERVER_PORT:8080}

weather.api.openweather.base-url=https://api.openweathermap.org/data/2.5/weather
weather.api.openweather.pro-url=https://pro.openweathermap.org/data/2.5/forecast
weather.api.openweather.geo-url=https://api.openweathermap.org/geo/1.0/direct
weather.api.openweather.key=${OPEN_WEATHER_API_KEY}