spring.application.name=weather

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/weatherForecast}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}

weather.api.openweather.base-url=https://api.openweathermap.org/data/2.5/weather
weather.api.openweather.pro-url=https://pro.openweathermap.org/data/2.5/forecast/hourly
weather.api.openweather.key=${OPEN_WEATHER_API_KEY}